{\rtf1\ansi\ansicpg1252\cocoartf2758
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red0\green0\blue0;\red44\green155\blue54;
\red20\green21\blue26;\red72\green168\blue181;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0\c83137;\cssrgb\c0\c0\c0\c7843;\cssrgb\c19608\c65882\c27451;
\cssrgb\c10196\c10588\c13333;\cssrgb\c33725\c71373\c76078;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs32 \cf2 \cb3 \expnd0\expndtw0\kerning0
[server]\
\pard\pardeftab720\partightenfactor0
\cf4 headless\cf2  = \cf5 true\cf2 \
port = \cf6 10000\cf2 \
\
[browser]\
serverAddress = \cf4 "0.0.0.0"\cf2 \
serverPort = \cf6 10000}